# Build the single Agents-panel line out of a hook payload.
# Input:  a PermissionRequest / PreToolUse / Elicitation payload
# Output: one string of at most 40 characters (use with jq -r)

def trunc($n):
  if (. | length) > $n then (.[0:$n-1] + "…") else . end;

def base: split("/") | last;

# Is this an MCP tool? tool_name has the shape `mcp__<server>__<tool>`
def is_mcp: (.tool_name // "") | startswith("mcp__");

# Strip the server part off an MCP tool name.
# Drop the first two segments ("mcp" and the server name) and rejoin the rest.
# `split("__") | last` would keep only the tail when the tool name itself
# contains __. A malformed name with too few separators yields an empty string,
# and the caller falls back to just the heading.
def mcp_tool: (.tool_name // "") | split("__") | .[2:] | join("__");

# The per-tool body. Empty string when nothing useful can be extracted.
def body:
  .tool_name as $t
  | (.tool_input // {}) as $i
  | if is_mcp then
      # A raw tool_name measured 48 characters, and the first 39 of those are
      # eaten by the prefix and server name. Emitted as-is it gets cut twice —
      # once by trunc(40), once by herdr's own width clamp — and **the display
      # becomes pure boilerplate without a single character telling you which
      # tool is blocking** (confirmed on a real machine). The information lives
      # in the trailing tool name, so keep only that.
      mcp_tool
    elif $t == "Bash" then
      ($i.description // $i.command // "")
    elif $t == "Edit" or $t == "Write" or $t == "Read" or $t == "NotebookEdit" then
      (($i.file_path // "") | if . == "" then "" else base end)
    elif $t == "AskUserQuestion" then
      ($i.questions[0].header // $i.questions[0].question // "")
    else
      ""
    end;

# The heading that leads the line. `label` is a jq keyword (label $out | break),
# so it cannot be used as the name here.
def heading:
  # Most tools emit .tool_name verbatim (Bash / Edit / …).
  # AskUserQuestion is the one we shorten — verbatim it is 15 characters, which
  # eats into both the 40-character cap and the sidebar width and truncates the
  # body that actually matters. Collapse MCP the same way; the Elicitation
  # branch already emits "MCP: ", so the vocabulary stays consistent.
  if is_mcp then "MCP"
  elif .tool_name == "AskUserQuestion" then "Question"
  else (.tool_name // "?") end;

if .hook_event_name == "Elicitation" then
  # Fallback for when neither message nor server name is available. This string
  # is generated by the plugin rather than coming from the user's payload.
  "MCP: " + (.message // .mcp_server_name // "input needed")
else
  (heading as $h | body as $b
   | if $b == "" then $h else ($h + ": " + $b) end)
end
| trunc(40)
